In [1]:
import numpy as np

1. Crie dois NumPy Arrays unidimensionais de tamanho 8: um formado apenas
por 1’s e outro formado por números aleatórios entre 0 e 9. Some estes dois
NumPy Arrays e guarde o resultado dentro de um terceiro NumPy Array. Por
fim, faça o seguinte:

  a. Se a soma de todos os elementos do Array resultante for >= 40, remodele este
  NumPy Array para se tornar uma matriz com mais linhas do que colunas. Senão,
  remodele para que se torne uma matriz com mais colunas do que linhas.

In [52]:
ones = np.ones(8)
random_namber = np.random.randint(0,9, 8)
sum_arr = ones + random_namber

if sum_arr.sum() >= 40:
  print(sum_arr.reshape(4,2))
else:
  print(sum_arr.reshape(2,4))


[[9. 4. 9. 4.]
 [2. 1. 9. 1.]]


2. Crie dois NumPy Arrays unidimensionais: um de números pares de 0 à 51 e
outro também de números pares de 100 até 50. Em seguida, os concatene e
mostre os resultados ordenados

In [56]:
even_numbers_0_51 = np.arange(0, 51, 2)
even_numbers_50_100 = np.arange(50, 100, 2)
even_numbers = np.concatenate((even_numbers_0_51, even_numbers_50_100))
print(even_numbers)


[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92
 94 96 98]


3. Mini Campo Minado

a) Crie um NumPy Array 2x2 formado apenas por 0’s

b) Em seguida, adicione um número 1 em uma posição aleatória desta matriz;

c) Faça uma entrada de dados para solicitar o usuário que faça uma jogada
(selecione uma posição da matriz)

I. Se ele selecionar todas as posições em que o número 1 não se encontra, mostre a
  mensagem “Congratulations! You beat the game! :)”
  
II. Senão, se dentro das 3 primeiras jogadas ele achar o número 1, mostre a mensagem
  “Game Over! :( Try Again!”

In [70]:
matriz = np.zeros([2,2])
row, col = np.random.randint(0, 2), np.random.randint(0, 2)
matriz[row, col] = 1
print(matriz)

games_played = 0


while True:
  try:
    user_row = int(input('Choose a row (0 or 1): '))
    user_column = int(input('Now, choose a column (0 or 1): '))

    if matriz[user_row, user_column] == 1:
      print('Congratulations! You beat the game!')
      break
    else:
      print('You missed! Try again!')
      games_played += 1
  
    if games_played == 3:
      print('You lost the game!')
      break
  except IndexError:
    print("Invalid input. Please enter 0 or 1 for both row and column.")






[[0. 0.]
 [0. 1.]]
Invalid input. Please enter 0 or 1 for both row and column.
Congratulations! You beat the game!


4. Crie uma matriz de tamanho qualquer. Extraia seu número de linhas e
colunas, multiplique-os, e diga se esta matriz poderia se tornar um vetor
unidimensional com número par ou ímpar de elementos

In [ ]:

rows = np.random.randint(1, 6)
cols = np.random.randint(1, 6)
matrix = np.random.randint(0, 10, (rows, cols))


num_rows, num_cols = matrix.shape
total_elements = num_rows * num_cols

if total_elements % 2 == 0:
    parity = "par"
else:
    parity = "ímpar"

print("Matriz:")
print(matrix)
print(f"\nA matriz tem {num_rows} linhas e {num_cols} colunas, totalizando {total_elements} elementos.")
print(f"Se convertida em um vetor unidimensional, terá um número {parity} de elementos.")

Matriz:
[[5 4 0 9 1]
 [6 4 6 8 0]
 [6 0 6 8 2]]

A matriz tem 3 linhas e 5 colunas, totalizando 15 elementos.
Se convertida em um vetor unidimensional, terá um número ímpar de elementos.


5. Crie uma matriz de tamanho 4x4 formada por números aleatórios inteiros
entre 1 e 50 (use seed = 10 antes)
a) Mostre o resultado da média de cada linha e cada coluna da matriz
gerada
b) c) Apresente o maior valor das médias das linhas e também das colunas
Mostre a quantidade de aparições de cada um dos números gerados na
matriz. Em seguida, mostre apenas os números que aparecem 2 vezes

In [1]:
import numpy as np
from collections import Counter

np.random.seed(10)
matriz = np.random.randint(1, 51, (4, 4))

medias_linhas = matriz.mean(axis=1)
medias_colunas = matriz.mean(axis=0)

maior_media_linhas = medias_linhas.max()
maior_media_colunas = medias_colunas.max()

contagem_numeros = Counter(matriz.flatten())

numeros_2_vezes = [num for num, count in contagem_numeros.items() if count == 2]

print("Matriz gerada:")
print(matriz)
print("\nMédias das linhas:", medias_linhas)
print("Médias das colunas:", medias_colunas)
print("\nMaior média das linhas:", maior_media_linhas)
print("Maior média das colunas:", maior_media_colunas)
print("\nContagem de números:", contagem_numeros)
print("Números que aparecem exatamente 2 vezes:", numeros_2_vezes)


Matriz gerada:
[[10 37 16  1]
 [50 29 26 30]
 [49 30 50  9]
 [10  1 43 41]]

Médias das linhas: [16.   33.75 34.5  23.75]
Médias das colunas: [29.75 24.25 33.75 20.25]

Maior média das linhas: 34.5
Maior média das colunas: 33.75

Contagem de números: Counter({np.int64(10): 2, np.int64(1): 2, np.int64(50): 2, np.int64(30): 2, np.int64(37): 1, np.int64(16): 1, np.int64(29): 1, np.int64(26): 1, np.int64(49): 1, np.int64(9): 1, np.int64(43): 1, np.int64(41): 1})
Números que aparecem exatamente 2 vezes: [np.int64(10), np.int64(1), np.int64(50), np.int64(30)]
